### ISSUE TITLE
Nexus Step Plugin fatal errors on Windows 2012 R2 / Rundeck Pro

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/nexus-step-plugins#8]
Same plugin v1.0.1 code that is running on RHEL7 / Rundeck 2.4.2 and is at least attempting to pull an artifact, is not working as well with Rundeck Pro on W2K12.

1: Workflow step executing: StepExecutionItem{type='nexus-exists-artifact-step', keepgoingOnSuccess=false, hasFailureHandler=false}
Failed executing step plugin [nexus-exists-artifact-step]: java.lang.NullPointerException
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:357)
	at groovyx.net.http.HTTPBuilder$request.call(Unknown Source)
	at com.simplifyops.rundeck.plugin.nexus.NexusExistsArtifactStepPlugin.executeStep(NexusExistsArtifactStepPlugin.groovy:91)
	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:98)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWFSection(NodeFirstWorkflowStrategy.java:313)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:119)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)

[workflow] Finish step: 1,nexus-exists-artifact-step
[workflow] Finish execution:  rundeck-workflow-node-first: [Workflow result: , step failures: {1=PluginFailed: null}, status: failed]
[Workflow result: , step failures: {1=PluginFailed: null}, status: failed]
Execution failed: 9: [Workflow result: , step failures: {1=PluginFailed: null}, status: failed]

framework.properties:
# ----------------------------------------------------------------
# Nexus Step Plugin config
# ----------------------------------------------------------------
framework.plugin.WorkflowStep.nexus-deliver-artifact-step.nexus=http://servername/tis611/
framework.plugin.WorkflowStep.nexus-deliver-artifact-step.nexusUser=user
framework.plugin.WorkflowStep.nexus-deliver-artifact-step.nexusPassword=pass
framework.plugin.WorkflowStep.nexus-register-delivery-step.modelDirPath=E:\\tmp

**Comment by zaox** [comment]
I have a same problem with Rundeck 2.6.9
Execution failed every job,
[Workflow result: , step failures: {1=PluginFailed: null}, flow control: Continue, status: failed]
